using Wms.Application.Common;

namespace Wms.Modules.Stock.Localization;

public sealed class StockLocalizationResource : ILocalizationResource
{
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> MessagesByCulture { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stock code already exists",
                ["StockCreatedSuccessfully"] = "Stock created successfully",
                ["StockDeletedSuccessfully"] = "Stock deleted successfully",
                ["StockDetailAlreadyExists"] = "Stock detail already exists for this stock",
                ["StockDetailCreatedSuccessfully"] = "Stock detail created successfully",
                ["StockDetailNotFound"] = "Stock detail not found",
                ["StockDetailRetrievedSuccessfully"] = "Stock detail retrieved successfully",
                ["StockDetailUpdatedSuccessfully"] = "Stock detail updated successfully",
                ["StockImageDeletedSuccessfully"] = "Stock image deleted successfully",
                ["StockImageFilesRequired"] = "At least one image file is required",
                ["StockImageNotFound"] = "Stock image not found",
                ["StockImagePrimaryUpdateFailed"] = "Primary stock image update failed",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Primary stock image updated successfully",
                ["StockImageUploadFailed"] = "Stock image upload failed",
                ["StockImagesRetrievedSuccessfully"] = "Stock images retrieved successfully",
                ["StockImagesUploadedSuccessfully"] = "Stock images uploaded successfully",
                ["StockNotFound"] = "Stock not found",
                ["StockRetrievedSuccessfully"] = "Stock records retrieved successfully",
                ["StockSyncCompletedSuccessfully"] = "Stock sync completed successfully",
                ["StockUpdatedSuccessfully"] = "Stock updated successfully",
            },
            ["tr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stok kodu zaten mevcut",
                ["StockCreatedSuccessfully"] = "Stok başarıyla oluşturuldu",
                ["StockDeletedSuccessfully"] = "Stok başarıyla silindi",
                ["StockDetailAlreadyExists"] = "Bu stok icin detay zaten mevcut",
                ["StockDetailCreatedSuccessfully"] = "Stok detayi basariyla olusturuldu",
                ["StockDetailNotFound"] = "Stok detayi bulunamadi",
                ["StockDetailRetrievedSuccessfully"] = "Stok detayi basariyla getirildi",
                ["StockDetailUpdatedSuccessfully"] = "Stok detayi basariyla guncellendi",
                ["StockImageDeletedSuccessfully"] = "Stok gorseli silindi",
                ["StockImageFilesRequired"] = "En az bir gorsel dosyasi zorunludur",
                ["StockImageNotFound"] = "Stok gorseli bulunamadi",
                ["StockImagePrimaryUpdateFailed"] = "Birincil stok gorseli guncellenemedi",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Birincil stok gorseli guncellendi",
                ["StockImageUploadFailed"] = "Stok gorseli yukleme basarisiz",
                ["StockImagesRetrievedSuccessfully"] = "Stok gorselleri basariyla getirildi",
                ["StockImagesUploadedSuccessfully"] = "Stok gorselleri basariyla yuklendi",
                ["StockNotFound"] = "Stok bulunamadı",
                ["StockRetrievedSuccessfully"] = "Stok kayıtları başarıyla getirildi",
                ["StockSyncCompletedSuccessfully"] = "Stok senkronizasyonu başarıyla tamamlandı",
                ["StockUpdatedSuccessfully"] = "Stok başarıyla güncellendi",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stock code already exists",
                ["StockCreatedSuccessfully"] = "Stock created successfully",
                ["StockDeletedSuccessfully"] = "Stock deleted successfully",
                ["StockDetailAlreadyExists"] = "Stock detail already exists for this stock",
                ["StockDetailCreatedSuccessfully"] = "Stock detail created successfully",
                ["StockDetailNotFound"] = "Stock detail not found",
                ["StockDetailRetrievedSuccessfully"] = "Stock detail retrieved successfully",
                ["StockDetailUpdatedSuccessfully"] = "Stock detail updated successfully",
                ["StockImageDeletedSuccessfully"] = "Stock image deleted successfully",
                ["StockImageFilesRequired"] = "At least one image file is required",
                ["StockImageNotFound"] = "Stock image not found",
                ["StockImagePrimaryUpdateFailed"] = "Primary stock image update failed",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Primary stock image updated successfully",
                ["StockImageUploadFailed"] = "Stock image upload failed",
                ["StockImagesRetrievedSuccessfully"] = "Stock images retrieved successfully",
                ["StockImagesUploadedSuccessfully"] = "Stock images uploaded successfully",
                ["StockNotFound"] = "Stock not found",
                ["StockRetrievedSuccessfully"] = "Stock records retrieved successfully",
                ["StockSyncCompletedSuccessfully"] = "Stock sync completed successfully",
                ["StockUpdatedSuccessfully"] = "Stock updated successfully",
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stock code already exists",
                ["StockCreatedSuccessfully"] = "Stock created successfully",
                ["StockDeletedSuccessfully"] = "Stock deleted successfully",
                ["StockDetailAlreadyExists"] = "Stock detail already exists for this stock",
                ["StockDetailCreatedSuccessfully"] = "Stock detail created successfully",
                ["StockDetailNotFound"] = "Stock detail not found",
                ["StockDetailRetrievedSuccessfully"] = "Stock detail retrieved successfully",
                ["StockDetailUpdatedSuccessfully"] = "Stock detail updated successfully",
                ["StockImageDeletedSuccessfully"] = "Stock image deleted successfully",
                ["StockImageFilesRequired"] = "At least one image file is required",
                ["StockImageNotFound"] = "Stock image not found",
                ["StockImagePrimaryUpdateFailed"] = "Primary stock image update failed",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Primary stock image updated successfully",
                ["StockImageUploadFailed"] = "Stock image upload failed",
                ["StockImagesRetrievedSuccessfully"] = "Stock images retrieved successfully",
                ["StockImagesUploadedSuccessfully"] = "Stock images uploaded successfully",
                ["StockNotFound"] = "Stock not found",
                ["StockRetrievedSuccessfully"] = "Stock records retrieved successfully",
                ["StockSyncCompletedSuccessfully"] = "Stock sync completed successfully",
                ["StockUpdatedSuccessfully"] = "Stock updated successfully",
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stock code already exists",
                ["StockCreatedSuccessfully"] = "Stock created successfully",
                ["StockDeletedSuccessfully"] = "Stock deleted successfully",
                ["StockDetailAlreadyExists"] = "Stock detail already exists for this stock",
                ["StockDetailCreatedSuccessfully"] = "Stock detail created successfully",
                ["StockDetailNotFound"] = "Stock detail not found",
                ["StockDetailRetrievedSuccessfully"] = "Stock detail retrieved successfully",
                ["StockDetailUpdatedSuccessfully"] = "Stock detail updated successfully",
                ["StockImageDeletedSuccessfully"] = "Stock image deleted successfully",
                ["StockImageFilesRequired"] = "At least one image file is required",
                ["StockImageNotFound"] = "Stock image not found",
                ["StockImagePrimaryUpdateFailed"] = "Primary stock image update failed",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Primary stock image updated successfully",
                ["StockImageUploadFailed"] = "Stock image upload failed",
                ["StockImagesRetrievedSuccessfully"] = "Stock images retrieved successfully",
                ["StockImagesUploadedSuccessfully"] = "Stock images uploaded successfully",
                ["StockNotFound"] = "Stock not found",
                ["StockRetrievedSuccessfully"] = "Stock records retrieved successfully",
                ["StockSyncCompletedSuccessfully"] = "Stock sync completed successfully",
                ["StockUpdatedSuccessfully"] = "Stock updated successfully",
            },
            ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["StockAlreadyExists"] = "ERP stock code already exists",
                ["StockCreatedSuccessfully"] = "Stock created successfully",
                ["StockDeletedSuccessfully"] = "Stock deleted successfully",
                ["StockDetailAlreadyExists"] = "Stock detail already exists for this stock",
                ["StockDetailCreatedSuccessfully"] = "Stock detail created successfully",
                ["StockDetailNotFound"] = "Stock detail not found",
                ["StockDetailRetrievedSuccessfully"] = "Stock detail retrieved successfully",
                ["StockDetailUpdatedSuccessfully"] = "Stock detail updated successfully",
                ["StockImageDeletedSuccessfully"] = "Stock image deleted successfully",
                ["StockImageFilesRequired"] = "At least one image file is required",
                ["StockImageNotFound"] = "Stock image not found",
                ["StockImagePrimaryUpdateFailed"] = "Primary stock image update failed",
                ["StockImagePrimaryUpdatedSuccessfully"] = "Primary stock image updated successfully",
                ["StockImageUploadFailed"] = "Stock image upload failed",
                ["StockImagesRetrievedSuccessfully"] = "Stock images retrieved successfully",
                ["StockImagesUploadedSuccessfully"] = "Stock images uploaded successfully",
                ["StockNotFound"] = "Stock not found",
                ["StockRetrievedSuccessfully"] = "Stock records retrieved successfully",
                ["StockSyncCompletedSuccessfully"] = "Stock sync completed successfully",
                ["StockUpdatedSuccessfully"] = "Stock updated successfully",
            },
        };
}